services:
  jelly-app:
    image: ghcr.io/Stannnnn/jelly-app:latest
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - VITE_DEFAULT_JELLYFIN_URL=${VITE_DEFAULT_JELLYFIN_URL}
      - VITE_LOCK_JELLYFIN_URL=${VITE_LOCK_JELLYFIN_URL}
