name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --build-arg VITE_DEFAULT_JELLYFIN_URL=https://media.poveycloud.top --build-arg VITE_LOCK_JELLYFIN_URL=true --tag jelly-app
