name: Build and Push Docker Image to GHCR

on:
    push:
        branches:
            - main
    release:
        types: [published]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: stannnnn/jelly-music-app

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set Docker image tags
              id: vars
              run: |
                  if [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
                    VERSION_TAG="${GITHUB_REF##*/}"
                    echo "TAGS=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION_TAG},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_ENV
                  elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
                    echo "TAGS=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main" >> $GITHUB_ENV
                  fi

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: ${{ env.TAGS }}
